Select 
	
	C.CITY AS ŞEHİRADI,
	SUM(OD.LINETOTAL) AS TOPLAM_SİPARİŞ_TUTARI,
	SUM(OD.AMOUNT) AS TOPLAM_SİPARİŞ_ADEDİ,
	COUNT(OD.ID) AS TOPLAM_SİPARİŞ_SAYISI

from ORDERS AS O

	INNER JOIN USERS AS U ON U.ID = O.USERID
	INNER JOIN ADDRESS AS A ON A.ID = O.ADDRESSID
	INNER JOIN CITIES AS C ON C.ID = A.CITYID
	INNER JOIN TOWNS AS T ON T.ID = A.TOWNID
	INNER JOIN DISTRICTS AS D ON D.ID = A.DISTRICTID
	INNER JOIN PAYMENTS AS P ON P.ORDERID = O.ID
	INNER JOIN INVOICES AS I ON I.ORDERID = O.ID 
	INNER JOIN ORDERDETAILS AS OD ON OD.ORDERID = O.ID 
	INNER JOIN ITEMS AS ITM ON ITM.ID = OD.ITEMID

--WHERE U.NAMESURNAME = 'M S'
--WHERE O.ID = 3314

GROUP BY C.CITY
ORDER BY C.CITY
